feat: Support runners with preconfigured credentials
cdklabs/cdk-pipelines-github pull request #372
Opened 2022-10-13 21:18 UTC by christophgysin

Fixes #371

2022-10-13 21:50 UTC, christophgysin commented on src/pipeline.ts
> +  readonly awsCredentials?: AwsCredentialsProvider;
This would be a breaking change. Please let me know if we can live with that, and I'll document it in the commit message.

2022-10-14 17:43 UTC, christophgysin commented on src/pipeline.ts
> +  readonly awsCredentials?: AwsCredentialsProvider;
Of course, I'll add it back and introduce a new property instead.

2022-10-19 14:10 UTC, kaizencc requested changes
Hi @christophgysin, this looks great! some minor nits here and there, and also please update the readme with these changes. Most of the readme examples should be updated to not use deprecated apis and we should list the new way of supplying preconfigured credentials as well.

2022-10-19 14:10 UTC, kaizencc commented on src/pipeline.ts
> +  private getAwsCredentials(props: GitHubWorkflowProps) {
Now that providing aws creds is convoluted with deprecated apis and such, I think it's necessary to have some checks here to make sure that the user is not supplying more than one of `githubActionRoleArn`, `awsCredentials`, or `awsCreds`.

2022-10-19 14:10 UTC, kaizencc commented on src/pipeline.ts
> +   * @deprecated Use `awsCreds` instead.
```suggestion
   * @deprecated Use `awsCreds.fromOpenIdConnect()` instead.
```

2022-10-19 14:10 UTC, kaizencc commented on src/pipeline.ts
> +   * @deprecated Use `awsCreds` instead.
```suggestion
   * @deprecated Use `awsCreds.fromGitHubSecrets()` instead.
```

2022-10-20 15:48 UTC, kaizencc approved these changes
Thanks @christophgysin! Really appreciate all your contributions thus far.

2022-10-20 15:55 UTC, merged