feat: option configure partition with env var
cdklabs/cdk-pipelines-github pull request #895
Opened 2024-02-27 12:17 UTC by mbergkvist

Adds support for deployment to aws-cn partition by checking an optional environemt variable, `CDK_AWS_PARTITION`. The partition is currently not available to the pipeline in the `jobForDeploy`, adding the environment variable is a non-breaking change to get the pipeline to deploy to aws-cn.

This has been verified with stacks and nested stacks in multiple stages in aws-cn.

Fixes #820

2024-02-27 12:19 UTC, mbergkvist commented
#868

2024-03-04 15:51 UTC, kaizencc requested changes
looks good, can we unit test this just for posterity?

2024-03-04 16:31 UTC, mbergkvist commented
> looks good, can we unit test this just for posterity?

Absolutely. I'll see what I can do.

> also, maybe a reference in the README would be helpful. doesn't have to be front and center, i don't imagine that many people in aws-cn are using this :)

Of course. I don't know why I didn't add it in the first place 🤦 
Any suggestion under what section this would belong?

2024-03-06 05:36 UTC, mbergkvist commented
@kaizencc I've updated the documentation, I'm not a technical writer though so feel free to update it.

I've also added test suites, I figured it would get good coverage by duplicating the current test suites that are relevant for the changes here, and tweaking them for the aws-cn case.

2024-03-13 06:00 UTC, mbergkvist commented
@kaizencc Is this ok to be merged?

2024-03-18 21:44 UTC, kaizencc commented on README.md
> +`.amazonaws.com.cn` instead of `.amazonaws.com.cn`.
```suggestion
`.amazonaws.com.cn` instead of `.amazonaws.com`.
```

2024-03-18 21:46 UTC, kaizencc approved these changes

2024-03-19 05:11 UTC, mbergkvist commented on README.md
> +`.amazonaws.com.cn` instead of `.amazonaws.com.cn`.
🤦‍♂️

2024-03-19 05:24 UTC, merged